# Generated by Django 2.0.2 on 2018-07-06 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interviewermodel',
            options={'permissions': (('interviwer', "Permissions that a candidate shouldn't have."),)},
        ),
        migrations.AddField(
            model_name='queryrequest',
            name='interviewer',
            field=models.CharField(default=None, max_length=300),
            preserve_default=False,
        ),
    ]
