# Generated by Django 2.0.2 on 2018-07-08 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidatemodel',
            options={},
        ),
        migrations.AlterModelOptions(
            name='interviewermodel',
            options={'permissions': (('interviewer', 'not an candidate'),)},
        ),
    ]
