# Generated by Django 2.0.5 on 2018-07-08 09:43

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0002_auto_20180706_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatemodel',
            name='available_dates',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='interviewermodel',
            name='available_dates',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='queryrequest',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendarapp.CandidateModel'),
        ),
        migrations.AlterField(
            model_name='queryrequest',
            name='interviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendarapp.InterviewerModel'),
        ),
    ]
