# Generated by Django 2.0.5 on 2018-07-08 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0004_auto_20180708_1403'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interviewermodel',
            options={'permissions': (('interviewer', "Permissions that a candidate shouldn't have."),)},
        ),
    ]
