# Generated by Django 2.0.5 on 2018-07-08 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0005_auto_20180708_1453'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interviewermodel',
            options={'permissions': (('interviewer', 'interviewer'),)},
        ),
    ]
